version: '3.7'
services:
  awesome_api:
      build:
          context: .
          dockerfile: Dockerfile
      container_name: awesome_api
      ports:
          - 3000:3000
  mongodb:
      image: mongo:latest
      container_name: mongodb


networks:
  default:
    external:
      name: opos
