version: '3.7'
services:
  awesome_api:
      build:
          context: .
          dockerfile: Dockerfile
      container_name: awesome_api
      ports:
          - 3000:3000
      volumes:
          - .:/usr/src/app/
      environment:
          - APP_ENV=prod
  mongodb:
      image: mongo:latest
      container_name: mongodb


networks:
  default:
    external:
      name: opos
